# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-10-03 04:15
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0008_auto_20160912_1520'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='status',
            field=models.IntegerField(choices=[(1, 'submitted'), (2, 'shipped'), (3, 'confirmed')], default=1),
        ),
    ]
